Repository GiTA-Client/GiTA, pull requests merged in 2018-03, with the labels that each got.

#26 [#7]add main view implementation
  css/mainview.css
  css/welcome.css
  js/mainview.js
  js/visualiser.js
  main.html
  main.js
  mainview.html
Labels: feature

#42 Update electron to 1.8.4
  package-lock.json
  package.json
Labels: critical, security

#47 Require messagebus from main process
  js/input_checker.js
  js/terminal.js
Labels: bug
